from __future__ import annotations

REASONING_MODE_IDENTIFIED_CAUSAL_EFFECT = "identified_causal_effect"
REASONING_MODE_SCM_SIMULATION = "scm_simulation"
REASONING_MODE_GRAPH_PROPAGATION = "graph_propagation"
REASONING_MODE_REDUCED_FORM_ESTIMATE = "reduced_form_estimate"
REASONING_MODE_CONDITIONAL_FORECAST = "conditional_forecast"
REASONING_MODE_HEURISTIC = "heuristic"
REASONING_MODE_STRUCTURAL_SEMANTICS = "structural_semantics"
REASONING_MODE_OBSERVATIONAL_PREDICTION = "observational_prediction"
REASONING_MODE_VALIDATION_GATE = "validation_gate"

CANONICAL_REASONING_MODES = (
    REASONING_MODE_IDENTIFIED_CAUSAL_EFFECT,
    REASONING_MODE_SCM_SIMULATION,
    REASONING_MODE_GRAPH_PROPAGATION,
    REASONING_MODE_REDUCED_FORM_ESTIMATE,
    REASONING_MODE_CONDITIONAL_FORECAST,
    REASONING_MODE_HEURISTIC,
    REASONING_MODE_STRUCTURAL_SEMANTICS,
    REASONING_MODE_OBSERVATIONAL_PREDICTION,
    REASONING_MODE_VALIDATION_GATE,
)

IDENTIFICATION_STATUS_IDENTIFIED = "identified"
IDENTIFICATION_STATUS_PARTIALLY_IDENTIFIED = "partially_identified"
IDENTIFICATION_STATUS_NOT_FORMALLY_IDENTIFIED = "not_formally_identified"
IDENTIFICATION_STATUS_NOT_APPLICABLE = "not_applicable"

CANONICAL_IDENTIFICATION_STATUSES = (
    IDENTIFICATION_STATUS_IDENTIFIED,
    IDENTIFICATION_STATUS_PARTIALLY_IDENTIFIED,
    IDENTIFICATION_STATUS_NOT_FORMALLY_IDENTIFIED,
    IDENTIFICATION_STATUS_NOT_APPLICABLE,
)

ASSUMPTION_CAUSAL_SUFFICIENCY = "causal_sufficiency"
ASSUMPTION_FAITHFULNESS = "faithfulness"
ASSUMPTION_ACYCLICITY = "acyclicity"
ASSUMPTION_STATIONARITY = "stationarity"
ASSUMPTION_LINEARITY = "linearity"
ASSUMPTION_NO_INSTANTANEOUS_EFFECTS = "no_instantaneous_effects"
ASSUMPTION_GRANGER_PREDICTIVE_CAUSALITY_ONLY = "granger_predictive_causality_only"
ASSUMPTION_NO_LATENT_CONFOUNDERS_ADDRESSED = "no_latent_confounders_addressed"
ASSUMPTION_HOMOGENEITY = "homogeneity"
ASSUMPTION_POSITIVITY = "positivity"
ASSUMPTION_CONSISTENCY = "consistency"
ASSUMPTION_NO_INTERFERENCE = "no_interference"
ASSUMPTION_MECHANISM_INVARIANCE_UNDER_INTERVENTION = (
    "mechanism_invariance_under_intervention"
)

CANONICAL_ASSUMPTIONS = (
    ASSUMPTION_CAUSAL_SUFFICIENCY,
    ASSUMPTION_FAITHFULNESS,
    ASSUMPTION_ACYCLICITY,
    ASSUMPTION_STATIONARITY,
    ASSUMPTION_LINEARITY,
    ASSUMPTION_NO_INSTANTANEOUS_EFFECTS,
    ASSUMPTION_GRANGER_PREDICTIVE_CAUSALITY_ONLY,
    ASSUMPTION_NO_LATENT_CONFOUNDERS_ADDRESSED,
    ASSUMPTION_HOMOGENEITY,
    ASSUMPTION_POSITIVITY,
    ASSUMPTION_CONSISTENCY,
    ASSUMPTION_NO_INTERFERENCE,
    ASSUMPTION_MECHANISM_INVARIANCE_UNDER_INTERVENTION,
)

MECHANISM_FAMILY_LINEAR = "linear"
MECHANISM_FAMILY_GBDT = "gbdt"
MECHANISM_FAMILY_NEURAL = "neural"
MECHANISM_FAMILY_GAM = "gam"
MECHANISM_FAMILY_NONE = "none"

CANONICAL_MECHANISM_FAMILIES = (
    MECHANISM_FAMILY_LINEAR,
    MECHANISM_FAMILY_GBDT,
    MECHANISM_FAMILY_NEURAL,
    MECHANISM_FAMILY_GAM,
    MECHANISM_FAMILY_NONE,
)

# Recommended spellings only. Algorithm naming remains open-world.
ALGORITHM_PCMCI = "PCMCI"
ALGORITHM_PC = "PC"
ALGORITHM_GES = "GES"
ALGORITHM_FCI = "FCI"
ALGORITHM_NOTEARS = "NOTEARS"
ALGORITHM_LINGAM = "LiNGAM"
ALGORITHM_VAR_GRANGER = "VAR-Granger"

RECOMMENDED_ALGORITHM_NAMES = (
    ALGORITHM_PCMCI,
    ALGORITHM_PC,
    ALGORITHM_GES,
    ALGORITHM_FCI,
    ALGORITHM_NOTEARS,
    ALGORITHM_LINGAM,
    ALGORITHM_VAR_GRANGER,
)

__all__ = [
    "ALGORITHM_FCI",
    "ALGORITHM_GES",
    "ALGORITHM_LINGAM",
    "ALGORITHM_NOTEARS",
    "ALGORITHM_PC",
    "ALGORITHM_PCMCI",
    "ALGORITHM_VAR_GRANGER",
    "ASSUMPTION_ACYCLICITY",
    "ASSUMPTION_CAUSAL_SUFFICIENCY",
    "ASSUMPTION_CONSISTENCY",
    "ASSUMPTION_FAITHFULNESS",
    "ASSUMPTION_GRANGER_PREDICTIVE_CAUSALITY_ONLY",
    "ASSUMPTION_HOMOGENEITY",
    "ASSUMPTION_LINEARITY",
    "ASSUMPTION_MECHANISM_INVARIANCE_UNDER_INTERVENTION",
    "ASSUMPTION_NO_INSTANTANEOUS_EFFECTS",
    "ASSUMPTION_NO_INTERFERENCE",
    "ASSUMPTION_NO_LATENT_CONFOUNDERS_ADDRESSED",
    "ASSUMPTION_POSITIVITY",
    "ASSUMPTION_STATIONARITY",
    "CANONICAL_ASSUMPTIONS",
    "CANONICAL_IDENTIFICATION_STATUSES",
    "CANONICAL_MECHANISM_FAMILIES",
    "CANONICAL_REASONING_MODES",
    "IDENTIFICATION_STATUS_IDENTIFIED",
    "IDENTIFICATION_STATUS_NOT_APPLICABLE",
    "IDENTIFICATION_STATUS_NOT_FORMALLY_IDENTIFIED",
    "IDENTIFICATION_STATUS_PARTIALLY_IDENTIFIED",
    "MECHANISM_FAMILY_GAM",
    "MECHANISM_FAMILY_GBDT",
    "MECHANISM_FAMILY_LINEAR",
    "MECHANISM_FAMILY_NEURAL",
    "MECHANISM_FAMILY_NONE",
    "RECOMMENDED_ALGORITHM_NAMES",
    "REASONING_MODE_CONDITIONAL_FORECAST",
    "REASONING_MODE_GRAPH_PROPAGATION",
    "REASONING_MODE_HEURISTIC",
    "REASONING_MODE_IDENTIFIED_CAUSAL_EFFECT",
    "REASONING_MODE_OBSERVATIONAL_PREDICTION",
    "REASONING_MODE_REDUCED_FORM_ESTIMATE",
    "REASONING_MODE_SCM_SIMULATION",
    "REASONING_MODE_STRUCTURAL_SEMANTICS",
    "REASONING_MODE_VALIDATION_GATE",
]
